<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BuildingBlock/BuildingBlock.Application/BuildingBlock.Application.csproj" />
    <ProjectReference Include="../../src/LawyerPlatform/LawyerPlatform.Domain/LawyerPlatform.Domain.csproj" />
    <ProjectReference Include="../../src/LawyerPlatform/LawyerPlatform.Application/LawyerPlatform.Application.csproj" />
    <ProjectReference Include="../../src/LawyerPlatform/LawyerPlatform.Infrastructure/LawyerPlatform.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
